<?php



/**
 * @file
 * A block module that displays recent blog and forum posts.
 */

 function current_posts_help($path,$arg){

 	switch ($path){

 		case "admin/help#current_posts":
 		return '' . t("Displays links to nodes created to this date"). '';
 		break;

 	}

 }
/**
* Implements hook_block_info()
*/

function current_posts_block_info(){
	$blocks['current_posts'] = array(
	//The name that will appear in the block list
	'info' => t('Current posts'),
	//Default setting
	'cache' => DRUPAL_CACHE_PER_ROLE,

	);
	return $blocks;
}

/**
 * Custom content function. 
 * 
 * Set beginning and end dates, retrieve posts from database
 * saved in that time period.
 * 
 * @return 
 *   A result set of the targeted posts.
 */

 function current_posts_content(){

 	//Get today's date
 	$today = getdate();

 	//Calculate the date a week ago
 	$start_time = mktime(0,0,0,$today['mon'],($today['mday'] - 7),$today['year']);
 	//Get all posts from one week ago to the present

 	$end_time = time();

 	$query = db_select('node','n')->fields('n',array('nid','title','created'))->condition('status',1)->condition('created',array($start_time,$end_time), 'BETWEEN')->orderBy('created','DESC')->execute();
 	return $query;
 }


function current_posts_block_view($delta=''){
	
	
	switch($delta){
		case 'current_posts':
		$block['subject'] = t('Current posts');
		if(user_access('access content')){
			//Retrieve and process data here.

			$result = current_posts_content();
			$items = array();

			foreach($result as $node){
				$items[] = array('data'=>l($node->title, 'node/' . $node->nid),);
			}

			if(empty($items)){
			$block['content'] = t('No posts available');
			}else{
				$block['content'] = theme('item_list',array('items' => $items));
			}
		}
		return $block;
	}
}












